### ISSUE TITLE
Jakob's Täglich activity in Februar / März 2018 

### ISSUE THREAD

**Issue by Yulianxia** [njxiaoganzi/Familie-Rieger-Xia#1]
Was macht Jakob nach Kita.

### Montag
- [Mutter und Kinderturnen in der Gymnastikhalle der Schule Goosacker](http://www.tus-osdorf.de/content/sportangebot/turnen/) 
Zeit: 16:30-17:30

### Dienstag
- Bücherhalle blankenese  

### Mittwoch
- [ Musikschule Peters ](http://www.musikschule-peters-hamburg.de/)
Zeit: 17:00-18:00

### Donnestag
- Friedmann besuchen 
Zeit: 15:30 - 17:00
### Freitag
-  Zuhause bleiben.

**Comment by njxiaoganzi** [comment]
Can you please show me again the dates when Musikschule will not take place? I know that on 09 May will be Musikschule, but I am not sure about tomorrow...
