### ISSUE TITLE
5 steps to bring Jakob to bed !

### ISSUE THREAD

**Issue by Yulianxia** [njxiaoganzi/Familie-Rieger-Xia#10]
1. Close Fensterladen and Gardine first. 
go to bed is not something we need to discuss with him. So we say it we just do it . 

2. You need to be Unnachgiebig and zart to do routine.  
  -- In bedroom doesn't mean our job finished, Pls don't relax yourself.  lying in bed like a corpse(der Leiche) will only make things difficult.

3. Brush teeth is the second step need to be done. **QUICK & UNNACHGIEBIG** .  difficult issue done earlier, will make everybody be less stressed.

4. if we quickly finish all and he still doesn't want to sleep, **einfach licht ausmachen. (no discussion)** when he is tired he will quickly fall asleep.

5.  just give him a entschlossen  Kuss then leave. He will still love you and he can sleep longer!
- if you want to ask him kiss you, do it daytime. no need to bummelte before sleep

 if you don't relax too early instead of bring him to sleep quickly, you will have more personal time to enjoy youself. **So do I** !

**Comment by Yulianxia** [comment]
- I suggest you training yourself to have GESAMTANSICHT. When he fall asleep very late the former day and get up early, we should already think about eat lunch and dinner earlier. 

- When we know he is tired, we don't play or kuscheln when the light on. Feel sleepy need to create a dark and quiet environment.  

- I really don't want to shout to you every evening, i want to have my own time. especially late he will stay kita shorter time, i will have even less time for myself, and i will freak out for sure if Evening routine so  difficult to be ausführen.

- quick and unnachgiebig, BITTE!!

**Comment by njxiaoganzi** [comment]
will be followed, except step 5, which will apply when you are back again
