### ISSUE TITLE
Plan for tomorrow 2nd May

### ISSUE THREAD

**Issue by njxiaoganzi** [njxiaoganzi/Familie-Rieger-Xia#12]
I will bring him to Kita in the morning. I will alsoe have a meeting with Mrs Weinert in order to discuss how we proceed in taking him out of the kita. Your flight is at 1610 from Hamburg so you need to be there around 1400. I will bring you to airport. After that I can fetch him from Kita. Ok?

**Comment by Yulianxia** [comment]
hao de
