### ISSUE TITLE
Flug Information

### ISSUE THREAD

**Issue by Yulianxia** [njxiaoganzi/Familie-Rieger-Xia#3]
![image](https://user-images.githubusercontent.com/24825916/37895711-6a1b7472-30e2-11e8-8b07-5c8e7ed93b0a.png)

02 Mai  Hamburg -Copenhagen - Shanghai 
17 Mai  Shanghai - Copenhagen -  Hamburg

**Comment by Yulianxia** [comment]
29/04, 01-02/05 is public holiday in china.

**Comment by njxiaoganzi** [comment]
Hao de. I have just applied officially for time off. All fine.
