### ISSUE TITLE
Jakob's Life Balance Rules

### ISSUE THREAD

**Issue by Yulianxia** [njxiaoganzi/Familie-Rieger-Xia#7]
1. Abendessen nicht zu viel geben. 
- If his stomach too full and go to bed immediately, he will feel uncomfortable and will not fall asleep. Usually he will turn around all the time. please be noticed that he might ate too much. I did massage for him. later he fall asleep soon.
- If he still want to eat after dinner, explain to him he will have stomach pain
2. Under 20 grad, **NO** short sleeve T-shirt & summer Hose

**Comment by njxiaoganzi** [comment]
i will do like yesterday. try to eat early, around 1830...then should not be so big problem.
